openapi: 3.1.0
info:
  title: My API with mTLS
  description: API secured with mutual TLS Authentication
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production Server

components:
  securitySchemes:
    mutualTLS:
      type: mutualTLS
      description: Mutual TLS Authentication with Client Certificate
  
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "healthy"

paths:
  /health:
    get:
      summary: Health Check
      description: Returns API health status
      security:
        - mutualTLS: []
      responses:
        "200":
          description: Service is up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        "401":
          description: Unauthorized - Invalid Client Certificate
        "403":
          description: Forbidden - Certificate not allowed
