openapi: 3.1.0
info:
  title: WriteOnly file 1
  version: 1.0.0
  description: An example API demonstrating the writeOnly property in OAS 3.1.

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true # This property will only be included in responses
          example: 123
        username:
          type: string
          example: johndoe
        password:
          type: string
          writeOnly: true # This property will only be sent in requests, never in responses
          example: secret123
        email:
          type: string
          example: johndoe@example.com
      required:
        - username
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 123
        username:
          type: string
          example: johndoe
        email:
          type: string
          example: johndoe@example.com
