openapi: 3.1.0
info:
  title: Example API
  version: 1.0.0
  description: An example API showcasing writeOnly and readOnly properties.

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          writeOnly: true # This will only be allowed in requests (for security reasons)
          example: secret123
        email:
          type: string
          example: johndoe@example.com
      required:
        - username
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          readOnly: true # This will only appear in responses, never in requests
          example: 123
        username:
          type: string
          example: johndoe
        email:
          type: string
          example: johndoe@example.com
