openapi: 3.1.0
info:
  title: API with Webhooks
  version: 1.0.0

servers:
  - url: https://api.example.com
    description: Production Server

paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

webhooks:
  newEvent:
    post:
      summary: Webhook for new events 2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/EventTypeA"
                - $ref: "#/components/schemas/EventTypeB"
          application/xml:
            schema:
              $ref: "#/components/schemas/EventTypeA"
      responses:
        "200":
          description: Acknowledged

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    EventTypeA:
      type: object
      properties:
        eventType:
          type: string
          enum: [A]
        data:
          type: string

    EventTypeB:
      type: object
      properties:
        eventType:
          type: string
          enum: [B]
        details:
          type: string
